theme: jekyll-theme-minimal
title: [Random walks of a physicist in biology]
description: [The personal website of Felix Barber. If you've come here to either learn a little about me, or to hear about some hot takes in biology, you're in the right place!]

social-network-links:
  email: "felixbarber@nyu.edu"
  github: felixbarber
  twitter: FelixBarber9
