theme: jekyll-theme-minimal
title: [Random walks of a physicist in biology]
description: [The personal website and hot takes of Felix Barber.]
avatar: "/assets/img/avatar-icon.png"

# By default, the image is cut into a circle. You can disable this behaviour by setting 'round-avatar: false'
round-avatar: true

social-network-links:
  email: "felixbarber@nyu.edu"
  github: felixbarber
  twitter: FelixBarber9
