theme: jekyll-theme-minimal
{% raw %}{% seo %}{% endraw %}
title: [Random walks of a physicist in biology]
description: [The personal website and hot takes of Felix Barber.]
logo: /profile_pic.JPG

social-network-links:
  email: "felixbarber@nyu.edu"
  github: felixbarber
  twitter: FelixBarber9
  linkedin: felix-barber
  
  # Select which social network share links to show in posts
share-links-active:
  twitter: true
  linkedin: true
